name: Deploy production exe

on:
  push:
    branches: 
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    # tai code ve vps
      - name: Checkout code
        uses: actions/checkout@v2
    # build code = docker tai vps sau do con BE se chay ow docker trong vps
      - name: Run `docker-compose`
        run: |
          cd Backend
          docker compose up --build -d
      # Xóa container nếu đang chạy
      - name: Stop & Remove container
        run: |
          docker stop fe-phuclh || true
          docker rm fe-phuclh || true
  
      # Xóa image cũ nếu tồn tại
      - name: Delete old image
        run: |
          cd Frontend
          docker rmi feprn || true
  
      # Build image mới
      - name: Build image
        run: |
          docker build -t feprn .
  
      # Chạy container mới
      - name: Run container
        run: |
          cd Frontend
          docker run -d -p 9712:80 --name fe-phuclh feprn
                
